spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/host
    username: root
    password: 1111

inet:
  timeout: 100

scheduler:
  cache: 1000 * 2
  ping: 1000 * 4

server:
  port: 7777
